---
version: 0.2
phases:
    install:
        commands:
            - apt-get update && apt-get -y install python-pip && pip install --upgrade python && pip install --upgrade awscli && sudo apt-get -y install jq
            - pip install slackclient
    pre_build:
        commands:
            - printenv
    build:
      commands:
        - export TARGET_PATH=$(pwd)
        - cd open_mpw_precheck/dependencies
        - sh build-docker.sh
        - cd $TARGET_DIR
        - ASSUME_ROLE_ARN="arn:aws:iam::${AWS::AccountId}:role/${AWS::Region}-${StackName}-DockerAssumeRole"
        - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test; exit 0`
        - export TEMP_ROLE
        - echo $TEMP_ROLE
        - docker run -v $(pwd):/usr/local/bin -v $TARGET_PATH:$TARGET_PATH -u $(id -u $USER):$(id -g $USER) open_mpw_prechecker:latest bash -c "python3 open_mpw_prechecker.py --skip_drc -t $TARGET_PATH"
        - output=$TARGET_PATH/checks/full_log.log
    post_build:
      commands:
        - python test.py
